# Rust project
language: rust
cache: cargo

rust:
- 1.21.0
- stable
- beta
- nightly
matrix:
  allow-failures:
  - rust: nightly

# Build & Test
env:
- RUST_TEST_THREADS=1

before_script: |
  cargo install rustfmt || true

script:
- cargo fmt -- --write-mode diff
- cargo build --verbose
- cargo test --verbose

# Upload coverage
after_success:
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" \
       && "$TRAVIS_RUST_VERSION" == "stable" \
       && "$TRAVIS_PULL_REQUEST" = "false" \
       && "$TRAVIS_BRANCH" == "master" \
       ]]; then
      bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      cargo tarpaulin --out Xml
      bash <(curl -s https://codecov.io/bash)
    fi
