# Rust project
language: rust
cache: cargo

rust:
- 1.21.0
matrix:
  allow-failures:
  - rust: nightly

# Build & Test
env:
- RUST_TEST_THREADS=1

before_script:
- export PATH="$HOME/.cargo/bin:$PATH"
- which rustfmt || true
- rustfmt --version || true
- cargo install --force rustfmt-nightly || true
- which rustfmt || true
- rustfmt --version

script:
- cargo fmt -- --write-mode=diff
- cargo build --verbose
- cargo test --verbose

# Upload coverage
after_success:
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" \
       && "$TRAVIS_RUST_VERSION" == "stable" \
       && "$TRAVIS_PULL_REQUEST" = "false" \
       && "$TRAVIS_BRANCH" == "master" \
       ]]; then
      bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      cargo tarpaulin --out Xml
      bash <(curl -s https://codecov.io/bash)
    fi
