# Rust project
language: rust
cache: cargo

rust:
- 1.21.0
matrix:
  allow-failures:
  - rust: nightly

# Build & Test
env:
- RUST_TEST_THREADS=1
script:
- cargo build --verbose
- cargo test --verbose
