# Rust project
language: rust
cache: cargo

rust:
- 1.22.0
- stable
- beta
- nightly
matrix:
  allow-failures:
  - rust: nightly

# Build & Test
env:
- RUST_TEST_THREADS=1

before_script:
- sudo add-apt-repository -y ppa:kubuntu-ppa/backports
- sudo apt-get update
- sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
- |
    wget https://github.com/SimonKagstrom/kcov/archive/v34.tar.gz &&
    tar xzf v34.tar.gz &&
    mkdir kcov-34/build &&
    cd kcov-34/build &&
    cmake .. &&
    make &&
    sudo make install &&
    cd ../..
- which cargo-make || cargo install cargo-make
- which cargo-coverage-annotations || cargo install cargo-coverage-annotations

script:
- cargo build --verbose
- cargo test --verbose
- cargo make coverage
- cargo coverage-annotations

# Upload coverage
after_success:
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" \
       && "$TRAVIS_RUST_VERSION" == "stable" \
       && "$TRAVIS_PULL_REQUEST" = "false" \
       && "$TRAVIS_BRANCH" == "master" \
       ]]; then
      bash <(curl -s https://codecov.io/bash)
    fi
