# Rust project
language: rust
cache: cargo

rust:
- 1.22.0
- stable
- beta
- nightly
matrix:
  allow-failures:
  - rust: nightly

# Build & Test
env:
- RUST_TEST_THREADS=1

before_script:
- which cargo-make || cargo install cargo-make
- which cargo-coverage-annotations || cargo install cargo-coverage-annotations

script:
- cargo build --verbose
- cargo test --verbose
- cargo make coverage
- cargo coverage-annotations

# Upload coverage
after_success:
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" \
       && "$TRAVIS_RUST_VERSION" == "stable" \
       && "$TRAVIS_PULL_REQUEST" = "false" \
       && "$TRAVIS_BRANCH" == "master" \
       ]]; then
      bash <(curl -s https://codecov.io/bash)
    fi
