[package]
edition = "2018"
name = "loggy"
version = "0.2.1"
authors = ["Oren Ben-Kiki <oren@ben-kiki.org>"]
description = "An opinionated library for developing and testing rust applications that use logging."
repository = "https://github.com/orenbenkiki/loggy"
readme = "README.md"
keywords = ["logging", "testing"]
categories = ["development-tools::debugging", "development-tools::testing"]
license = "MIT"

[dependencies]
lazy_static = "^1.0.0"
log = "^0.3.1"
time = "^0.1.25"
unindent = "^0.1.2"
