[env]
RUST_TEST_THREADS = "1"
CARGO_MAKE_RUN_CODECOV = "true"

[tasks.coverage-annotations-flow]
description = "Runs the full coverage-annotations flow."
dependencies = ["test", "coverage", "coverage-annotations"]

[tasks.coverage-annotations]
description = "Verify the coverage annotations in the code"
install_crate = "cargo-coverage-annotations"
command = "cargo"
args = ["coverage-annotations"]

[tasks.pre-coverage]
run_task = "test"

[tasks.post-coverage]
run_task = "coverage-annotations"

[tasks.post-test]
run_task = "coverage-annotations-flow"

[tasks.format]
dependencies = ["format-nightly"]
